### ISSUE TITLE
there is  bug  when i use  this  project。

### ISSUE THREAD

**Issue by wangxuyang518** [fingdo/stateLayout#2]
first  i  use  “   emptyLayout.showLoadingView();”，after  i   receive  a  eventbus。I use  “  emptyLayout.showNoNetworkView();”      it  does  not  make  work

**Comment by fingdo** [comment]
复制一下你的错误信息给我，如果方便展示一下你的代码。我方便定位问题，tks

**Comment by wangxuyang518** [comment]
没得错误信息。就是加载不出来、、接受eventbus事件之后。然后设置网络错误 直接调用showNoNetWorke然后没得反应、、、

**Comment by fingdo** [comment]
eventbus的类型是什么，这个应该在ui线程去操作。

**Comment by wangxuyang518** [comment]
是主线程    加一个qq  1044393721  我给你截图

**Comment by fingdo** [comment]
有验证问题

**Comment by wangxuyang518** [comment]
我加你

**Comment by fingdo** [comment]
178357820
