### ISSUE TITLE
单独加载一个自定布局时,就失效

### ISSUE THREAD

**Issue by BruseDu** [fingdo/stateLayout#3]
View view = View.inflate(this, R.layout.activity_custom, null);
stateLayout.showCustomView(view);

**Comment by fingdo** [comment]
的确有这个问题，马上修复，修复了会通知你

**Comment by fingdo** [comment]
@BruseDu 已修复，请查看。[version 1.0.3](https://github.com/fingdo/stateLayout/releases/tag/1.0.3)
