### ISSUE TITLE
设置自定义loadingview 问题

### ISSUE THREAD

**Issue by Linkaaaa** [fingdo/stateLayout#4]
请问下为什么后面的版本设置自定义loadingview 只是把原来的图片修改了 下面的文本还在啊.  代码如下: View viewLoading = View.inflate(mContext, R.layout.alert_dialog, null);
        stateLayout.setLoadingView(viewLoading);
        stateLayout.showLoadingView(viewLoading); 这样设置后除了显示自定义的布局后下面还是有原来的提示本文

**Comment by fingdo** [comment]
确实是有这个问题，马上修复，十分钟后通知你

**Comment by Linkaaaa** [comment]
收到!3q

**Comment by fingdo** [comment]
好了，请调用`showLoadingView(View view, boolean showTip)`，第一个参数是自定义的loadingView，第二个是是否隐藏提示文本。这个showLoadingView的本意是让你们可以自定义替换自己的加载动画的。
依赖`compile 'com.github.fingdo:stateLayout:1.0.4'`

**Comment by Linkaaaa** [comment]
ok 谢谢
